### PR TITLE
npm publish

### PR DESCRIPTION
**Pull request by parc02**
- [x] first deploy

### CODE REVIEW

**Comment by parc02** [comment]
LGTM

**Comment by raheego** [comment]
https://i.lgtm.fun/2oc5.png

**Comment by yjinlee99** [comment]
[parc02](https://github.com/parc02)

**Comment by raheego** [comment]
LGTM

**Comment by raheego** [comment]
LGTM

**Comment by yjinlee99** [comment]
LGTM

**Comment by INAUGURATE-Ryong** [comment]
LGTM

**Comment by INAUGURATE-Ryong** [comment]
LGTM

**Comment by raheego** [comment]
LGTM

**Comment by raheego** [comment]
민성

**Pull request merged**
